apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment-app.yaml
- service-app.yaml
- ingress-app.yaml
- deployment-csv-importer.yaml
- service-csv-importer.yaml
- ingress-csv-importer.yaml